languageCode = "en-us"
title = "COM402 Advanced Web Design"
baseurl = "http://com402.kellyannepipe.me/"
theme = "hugo-theme-learn"
publishDir = "docs"
[params]
  currentclass = "class13"
  menu = [ "class-info", 
           "assignments", 
           ##"class42",
           ## "class41",
           ## "class40",
           ## "class39",
           ## "class38",
           ## "class37",
           ## "class36",
           ## "class35",
           ## "class34",
           ## "class33",
           ## "class32",
           ## "class31",
           ## "class30",
           ## "class29",
           ## "class28",
           ## "class27",
           ## "class26",
           ## "class25",
           ## "class24",
           ## "class23",
           ## "class22",
           ## "class21",
           ## "class20",
           ## "class19",
           ## "class18",
           ## "class17",
           ## "class16",
           ## "class15",
           ## "class14",
            "class13",
            "class12",
            "class11",
            "class10",
            "class09",
            "class08",
            "class07",
            "class06",
            "class05",
            "class04",
            "class03",
            "class02",
            "class01" ]
